### ISSUE TITLE
前瞻計畫書封面

### ISSUE THREAD

**Issue by jasjas110** [watchout-tw/musou-aux#2]
<img width="462" alt="2017-06-23 4 12 32" src="https://user-images.githubusercontent.com/26052751/27473538-2221842e-5832-11e7-844c-ec6eba1a53d6.png">

**Comment by chihhhhhao** [comment]
這是用issue當圖床的意思嗎？

**Comment by jasjas110** [comment]
我還在研究啦！

**Comment by chihhhhhao** [comment]
其實我覺得是個好主意耶 😆

**Comment by jasjas110** [comment]
這樣issue會爆炸吧？而且放在這邊不是反而不直觀（問號臉）

**Comment by chihhhhhao** [comment]
是蠻暴力的，不過如果只是快速需要一張圖，倒是不錯的解法（？）
